# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=30)),
                ('flyer', models.FileField(blank=True, null=True, upload_to='evento/%Y/%m/%d/')),
            ],
        ),
    ]
