# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20160826_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha']},
        ),
    ]
