# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20160827_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
