# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='direccion',
        ),
    ]
