# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_evento_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='evento/%Y/%m/%d/'),
        ),
    ]
