# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0002_auto_20160922_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='integrante/%Y/%m/%d/'),
        ),
    ]
