# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/%Y/%m/%d/')),
                ('descripcion', models.TextField(max_length=50)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
